### ISSUE TITLE
Update the project to .NET Core 2

### ISSUE THREAD

**Issue by agriffard** [lukaskabrt/PoExtractor#1]
Could you update the code to use packages from .NET Core?

When I open the solution, there is currently an error with the dependency "Microsoft.AspNet.Razor" that is targeting .NET 4.6.1

This might inspire you: https://github.com/aspnet/Razor/tree/dev/src/RazorPageGenerator
Ask @NTaylorMullen if you need help, I am sure he will be happy to answer your questions.

This dotnet tool to extract .po files from OrchardCore projects (classes and views) will be really useful.

**Comment by agriffard** [comment]
@lukaskabrt Can you please look at this issue?

**Comment by lukaskabrt** [comment]
Updated to the .NET Core 2
