### ISSUE TITLE
Make PoExtractor a dotnet tool

### ISSUE THREAD

**Issue by agriffard** [lukaskabrt/PoExtractor#10]
It would be great if PoExtractor was published on Nuget as a dotnet tool to make it easier to use.

Thanks to this, no need to get the sources, you just have to install it with the CLI.

**Comment by lukaskabrt** [comment]
It's a good idea. I was thinking about publishing binaries here on GitHub, but a dotnet tool is probably an even better solution.

**Comment by lukaskabrt** [comment]
Fixed by #12 

Installation instructions are in the Readme file
