### ISSUE TITLE
Detect StringLocalizer other than T[""] in OC

### ISSUE THREAD

**Issue by agriffard** [lukaskabrt/PoExtractor#15]
In OC, some IStringLocalizer are called `S` or `TS`, not `T`. Some IHtmlLocalizer are called `H` or `TH`.

Could it be possible to also detect this kind of localized strings:
`S["Configuration"]`
`TS["At least one content type must be selected."]`
`H["Deployment plan step added successfully"]`
`TH["Role deleted successfully"]`

Another case not detected is when string interpolation is used.
There are not many uses but it would be interesting to detect strings like this:
`T[$"{title}"]`

**Comment by lukaskabrt** [comment]
It isn't problem to add additional names for the IStringLocalizer. Out of curiosity ... is there any practical reason, why the names aren't unified?

I don't see any meaningful use case for interpolated strings. When `T[$"Title: {title}"]` is called, the string is processed first, so `IStringLocalizer` is called with the actual value of `title`. E.g. `T["Title: My blog post"]`. To make it work, you need to have the string `Title: My blog post` in the dictionary. 

IMO you should use `T["Title: {0}", title]`. It works in the same way as `string.Format`

**Comment by agriffard** [comment]
Indeed, there should be a common way to name it, like T, but for example, sometimes, there are a IStringLocalizer T and a IHtmlLocalizer TH in the same class.

For string interpolation, it was an example I found in a Command and, as far as I am concerned, I also like it but if you say it will be interpreted before the translation, we should not use it.

**Comment by lukaskabrt** [comment]
New localizer accessors `T`, `S`, `TS`, `H` and `TH` are supported in the latest version of the tool.

I have also removed interpolated strings from calls of IStringLocalizer in OC https://github.com/OrchardCMS/OrchardCore/pull/3160
