### ISSUE TITLE
Can we extract data annotation

### ISSUE THREAD

**Issue by Ahmed-Galal85** [lukaskabrt/PoExtractor#17]
Can we extract data annotation
Example
```
[Display(Name = "Id")]
public int? Id { get; set; }

```

**Comment by lukaskabrt** [comment]
There isn't any built-in functionality to extract data from attributes, but it is certainly possible. You can write your own extractor, that processes `AttributeSyntax` nodes. It will be very similar to `SingularStringExtractor` (https://github.com/lukaskabrt/PoExtractor/blob/dev/PoExtractor.CS/SingularStringExtractor.cs)

**Comment by Ahmed-Galal85** [comment]
@lukaskabrt 
Thanks, I did it
`public class DataAnnotationStringExtractor : LocalizableStringExtractor<SyntaxNode>
    {
        public DataAnnotationStringExtractor(IMetadataProvider<SyntaxNode> metadataProvider) : base(metadataProvider)
        {
        }

        public override bool TryExtract(SyntaxNode node, out LocalizableStringOccurence result)
        {
            result = null;
            if (node is AttributeArgumentSyntax accessor &&
                accessor.Expression is LiteralExpressionSyntax literal && 
                literal.IsKind(SyntaxKind.StringLiteralExpression) 
                && (node.ToFullString().StartsWith("Name=") || node.ToFullString().StartsWith("Name =")))
            {
                result = new LocalizableStringOccurence()
                {
                    Text = literal.Token.ValueText,
                    Context = this.MetadataProvider.GetContext(node),
                    Location = this.MetadataProvider.GetLocation(node),
                };

                return true;
            }
            return false;
        `

**Comment by Ahmed-Galal85** [comment]
@lukaskabrt 
**Thanks**, I did it.
![image](https://user-images.githubusercontent.com/9842272/67275839-b856b100-f4c3-11e9-80eb-19b3a75c627b.png)

**Comment by hishamco** [comment]
@lukaskabrt can I send a PR for this, while I'm working with data annotations in Orchard Core
