### ISSUE TITLE
Extract localized strings from VB file

### ISSUE THREAD

**Issue by hishamco** [lukaskabrt/PoExtractor#19]
Orchard Core could use VB files for controllers, view models .. etc, it would be nice if we add the ability to extract the localized strings from vb files

I can send a PR for this if sound looks good for you

**Comment by lukaskabrt** [comment]
@hishamco if you think it is worth the effort (not sure how widely is VB used), I will be happy to accept PR. It will be great addition to this project.

**Comment by hishamco** [comment]
The VB is widely used, but the limitation with view engine will reduce the number of the devs, nothing but while OC can use liquid, so the view engine is not depend on C# anymore, this addition will be useful

**Comment by hishamco** [comment]
FYI I 'll become a very active contributor to this project
