### ISSUE TITLE
PoExtraction.OrchardCore throws System.ArgumentException

### ISSUE THREAD

**Issue by ArieGato** [lukaskabrt/PoExtractor#26]
Hi,

when I use the PoExtractor for OrchardCore I get an exception for liquid templates. I used the following command to install:
```
dotnet tool install --global PoExtractor.OrchardCore --version 0.2.0-rc1
```

To determining the cause of the issue I cloned the PoExtractor repo and upgraded all packages. Same error keeps occuring. Then I tested on a Module of OrchardCore. The issue also occurs in the OrchardCore.Menu module.

The file that causes the issue is: /Views/LinkMenuItemPart.Admin.cshtml

Contents:
```
@{
    LinkMenuItemPart part = Model.MenuItemPart;
}

<span>@part.Name <code>@part.Url</code><span class="text-muted">- Link</span></span>
```
System.ArgumentException: 'An item with the same key has already been added. Key: functions'

Hope you can take a look at it.

Thnx,
Arjan

**Comment by hishamco** [comment]
@ArieGato is this still happening?

**Comment by ArieGato** [comment]
Yes the issue still occurs.

**Comment by hishamco** [comment]
Could you please provide me a repo to reproduce the this issue or at least a class or a view, coz frankly I'm not sure if the `0.2.0-rc1` is the latest version

**Comment by ArieGato** [comment]
sure, although I tested it with the latest version of the dev branch.

**Comment by hishamco** [comment]
Please refer me to the cs file or the view that causes the issue, I will do a unit test to make sure if there's a bug

**Comment by ArieGato** [comment]
I forked the repo here: https://github.com/ArieGato/PoExtractor

To reproduce:

1. adjust tje launchsettings to point to your OrchardCore solution
2. create a c:\temp\test folder
3. run the PoExtractor.OrchardCore

Now wait until the exception occurs. Some modules will be processed correctly.

**Comment by hishamco** [comment]
I will check ...

**Comment by hishamco** [comment]
That means if I run the `PoExtractor` on OC source some errors will show up?

**Comment by ArieGato** [comment]
yes, it should. In my case it happened at the OrchardCore.Admin project on the view AdminDashboard.cshtml.

**Comment by hishamco** [comment]
Let me have to the `AdminDahsboard.cshml` first before I run it

**Comment by hishamco** [comment]
Nothing strange on that view .. time to run the tool

**Comment by hishamco** [comment]
I just found one error

![Error](https://user-images.githubusercontent.com/3237266/78129647-95400e00-7420-11ea-8d2e-252d024eb59a.jpg)

This is not `ArgumentExceptions`?

**Comment by ArieGato** [comment]
![image](https://user-images.githubusercontent.com/1059562/78130243-3a56e880-7419-11ea-9c4f-21294fbd62ff.png)
![image](https://user-images.githubusercontent.com/1059562/78130254-3fb43300-7419-11ea-87f7-e29463a4d06d.png)

**Comment by ArieGato** [comment]
did you use my repo to test?

**Comment by hishamco** [comment]
No worry, I will debug 

> did you use my repo to test?
Nope, but the OC version may different from mine, I need to test it against the latest bits of the `dev` branch

**Comment by jptissot** [comment]
@ArieGato  @hishamco  I fixed it in https://github.com/lukaskabrt/PoExtractor/pull/34
