### ISSUE TITLE
Missing translations from .cshtml files

### ISSUE THREAD

**Issue by agriffard** [lukaskabrt/PoExtractor#31]
With the latest prerelease (https://www.nuget.org/packages/PoExtractor.OrchardCore/0.3.0-beta3-71077) or release (https://www.nuget.org/packages/PoExtractor.OrchardCore/0.2.0) versions of the dot net tool, some tanslations in .cshtml files are not generated when we execute :
`extractpo-oc D:\Orchard\OrchardCore C:\temp\OrchardCore --liquid`

Ex: It removes the strings that exist in .cshtml files in OrchardCore.Admin and many others.

Can you please have a look @lukaskabrt ?

**Comment by lukaskabrt** [comment]
@hishamco removed `T` accessor in PR #25 because according to https://github.com/OrchardCMS/OrchardCore/pull/5182#issuecomment-570379047, there should be a new convention for names of localizer accessors.

If `T` is still used in some places, I can add it back ...

**Comment by agriffard** [comment]
Yes, please readd it, it is still used everywhere.

**Comment by hishamco** [comment]
> @hishamco removed T accessor in PR #25

I think I remove them from code not the view, let me double check again

> Yes, please readd it, it is still used everywhere.

My suggestion to fix it in OC because we already started this, furthermore we can create a code analyzer to fix such issue

If sound is good I can start work on it, meanwhile I can scan entire OC source to remove the inconsistent localizer names

**Comment by lukaskabrt** [comment]
I added `T` back in #32. If it is removed from OC, it can be removed from PoExtractor again.

**Comment by agriffard** [comment]
Thank you @lukaskabrt

**Comment by hishamco** [comment]
> I added T back in #32 

No need to remove `T` at all because it will be used in the views only
