### ISSUE TITLE
Generate translations from .liquid files

### ISSUE THREAD

**Issue by agriffard** [lukaskabrt/PoExtractor#4]
Can you generate .po files by inspecting the .liquid files in Views?

The pattern would be like this:
`{{ "string to be localized" | t }}`

**Comment by lukaskabrt** [comment]
I don't want to parse liquid files myself and Fluid library doesn't expose filter names right now (https://github.com/sebastienros/fluid/pull/96). But I will try to generate .po files with a custom build of the Fluid library.

**Comment by lukaskabrt** [comment]
Support for .liquid files merged to the master

**Comment by lukaskabrt** [comment]
There is still some issue with assemblies versions

**Comment by lukaskabrt** [comment]
Fixed in the version 0.1.0
