### ISSUE TITLE
.net 5 support

### ISSUE THREAD

**Issue by tanekim77** [lukaskabrt/PoExtractor#42]
.net 5 is about to be officially released.
I tried to install PoExtractor from nuget for .net 5 preview project, but it says it's not compatible .
Having .net 5 support would be awesome.

**Comment by lukaskabrt** [comment]
.NET 5 support is on my to-do list. I will add support when .NET 5 is released.

**Comment by tanekim77** [comment]
@lukaskabrt 
Thanks!, .NET5 is released now :)

**Comment by pgrm** [comment]
@lukaskabrt FYI I updated it for myself to .net 5 and there was no code change necessary: https://github.com/pgrm/PoExtractor/commit/22bb65064a561dfa0bbc1d7ad0c5672d88b4a7ef - however, I understand that you'd also need to update the rest of the tool chain, like the build server config

**Comment by lukaskabrt** [comment]
.NET 5 support  added in #44 It will be available on Nuget with the next release.
