### ISSUE TITLE
Extract Liquid strings

### ISSUE THREAD

**Issue by agriffard** [lukaskabrt/PoExtractor#43]
A string like this `{{ "mystring" | t }}` does not seem to be extracted.

It only works with `{% assign mystring = "mystring" | t %}`.

**Comment by lukaskabrt** [comment]
I have added tests for parsing .liquid files in #45 and it seems that both variants are working. 

Can you give me a file that isn't processed correctly?

**Comment by agriffard** [comment]
OK, I updated to the latest version and it is ok now.
