### ISSUE TITLE
Release latest version

### ISSUE THREAD

**Issue by pgrm** [lukaskabrt/PoExtractor#50]
@lukaskabrt there were few improvements to this tool since the last release 11 months ago. Would you mind packaging them up into a new release and publish it in nuget? See for instance #49, which could be closed as well

Thank you!

**Comment by jmglezgz** [comment]
Hi guys, I'm not sure how to use PoExtractor with DataNotations,  I have an entry  [Display(Name="blah")] in one of my classes but when I execute PoExtractor that string is not found.

I'm using the latest code as @rjpowers10  commented, and PoExtractor is working fine for localizer strings.

Am I missing something in the configuration? 

Thanks
