### ISSUE TITLE
It is suggested to add some labels, such as "Orchard Core"

### ISSUE THREAD

**Issue by hyzx86** [lukaskabrt/PoExtractor#9]
Many people can't find this project.

**Comment by lukaskabrt** [comment]
I have added the tag `orchardcore`. Thanks for the tip.

@agriffard I am not sure, what is the best place in the docs to explain the translation workflow. `OrchardCore/src/OrchardCore.Modules/OrchardCore.Localization/README.md`? Or should I create a separate page? Let me know your preferences please and once I convert the project to a dotnet tool I will make a pull request with the documentation.

**Comment by agriffard** [comment]
Good.

Ok, so we could explain how to use the Crowdin localizations in OrchardCore.Localization/README.md and dedicate another page in the src/docs folder just to explain how to generate the files when the dotnet tool is a available.

**Comment by lukaskabrt** [comment]
I see the tool and process of creating PO files is already described in the documentation (https://orchardcore.readthedocs.io/en/dev/docs/reference/modules/Localize/)
